server:
  error:
    whitelabel:
      enabled: true
  port: 80

spring:
  data:
    mongodb:
      uri: ${CNAT_TRACKER_SERVICE_MONGODB_URI}
      database: cnat-tracker-service-db
  kafka:
    bootstrap-servers: ${CNAT_KAFKA_URI}
    consumer:
      group-id: "tracker"

app:
  kafka:
    topics:
      tracker-data-register: tracker-data-register