server:
  error:
    whitelabel:
      enabled: true
  port: 8081

spring:
  data:
    mongodb:
      uri: #mongodb://user:pass@host:27017
      database: cnat-tracker-service-db
  kafka:
    bootstrap-servers: #host:9092
    consumer:
      group-id: "tracker"

app:
  kafka:
    topics:
      tracker-data-register: tracker-data-register
