server:
  error:
    whitelabel:
      enabled: true
  port: 80

spring:
  data:
    mongodb:
      uri: ${CNAT_TRACKER_SERVICE_MONGODB_URI}
      database: ${CNAT_TRACKER_SERVICE_MONGODB_DATABASE}
      auto-index-creation: true
  kafka:
    bootstrap-servers: ${CNAT_KAFKA_URI}
    consumer:
      group-id: "tracker"

app:
  kafka:
    topics:
      tracker-data-register: tracker-data-register
