server:
  error:
    include-message: always
  port: 80

spring:
  data:
    mongodb:
      uri: ${CNAT_TRACKER_SERVICE_MONGODB_URI}
      database: ${CNAT_TRACKER_SERVICE_MONGODB_DATABASE}
      auto-index-creation: true
  kafka:
    bootstrap-servers: ${CNAT_KAFKA_URI}
    consumer:
      group-id: ${CNAT_TRACKER_SERVICE_KAFKA_CONSUMER_GROUP_ID}
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            use:
              type:
                headers: false

management:
  endpoint:
    health:
      #show-details: always
      probes:
        enabled: true

app:
  kafka:
    topics:
      tracker-data-register: ${CNAT_KAFKA_TRACKER_DATA_TOPIC}
